/**
 * data.js - Mock Data for Xperiencestore
 * Contains all mock data for products, orders, users, suppliers, etc.
 */

export const Data = {
  // Product Categories
  categories: [
    {
      id: 1,
      name: "Electronics",
      slug: "electronics",
      icon: "cpu",
      count: 245,
    },
    { id: 2, name: "Fashion", slug: "fashion", icon: "shirt", count: 189 },
    {
      id: 3,
      name: "Home & Office",
      slug: "home-office",
      icon: "home",
      count: 156,
    },
    {
      id: 4,
      name: "Industrial Parts",
      slug: "industrial",
      icon: "cog",
      count: 98,
    },
    {
      id: 5,
      name: "Sports & Outdoor",
      slug: "sports",
      icon: "dumbbell",
      count: 134,
    },
    {
      id: 6,
      name: "Health & Beauty",
      slug: "health",
      icon: "heart",
      count: 167,
    },
  ],

  // Products
  products: [
    {
      id: 1,
      name: "Wireless Bluetooth Headphones",
      slug: "wireless-bluetooth-headphones",
      category: "Electronics",
      categoryId: 1,
      price: 89.99,
      bulkPrice: 65.0,
      moq: 50,
      stock: 1250,
      rating: 4.5,
      reviews: 328,
      image:
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600",
      images: [
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600",
        "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600",
        "https://images.unsplash.com/photo-1545127398-14699f92334b?w=600",
      ],
      description:
        "Premium wireless headphones with active noise cancellation, 30-hour battery life, and superior sound quality.",
      features: [
        "Active Noise Cancellation",
        "30-Hour Battery",
        "Bluetooth 5.0",
        "Foldable Design",
      ],
      sku: "XP-WH-001",
      weight: "250g",
      dimensions: "20x18x8 cm",
      supplierId: 1,
      supplierName: "TechGlobal Electronics",
    },
    {
      id: 2,
      name: "Smart Fitness Watch",
      slug: "smart-fitness-watch",
      category: "Electronics",
      categoryId: 1,
      price: 129.99,
      bulkPrice: 95.0,
      moq: 30,
      stock: 890,
      rating: 4.7,
      reviews: 512,
      image:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
      images: [
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
        "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=600",
      ],
      description:
        "Track your fitness goals with heart rate monitoring, GPS, and 50+ sport modes.",
      features: [
        "Heart Rate Monitor",
        "GPS Tracking",
        "50+ Sport Modes",
        "Water Resistant",
      ],
      sku: "XP-FW-002",
      weight: "45g",
      dimensions: "4.5x4.5x1.2 cm",
      supplierId: 1,
      supplierName: "TechGlobal Electronics",
    },
    {
      id: 3,
      name: "Ergonomic Office Chair",
      slug: "ergonomic-office-chair",
      category: "Home & Office",
      categoryId: 3,
      price: 299.99,
      bulkPrice: 220.0,
      moq: 20,
      stock: 340,
      rating: 4.8,
      reviews: 189,
      image:
        "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600",
      images: [
        "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600",
        "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600",
      ],
      description:
        "Premium ergonomic chair with lumbar support, adjustable armrests, and breathable mesh.",
      features: [
        "Lumbar Support",
        "Adjustable Height",
        "Breathable Mesh",
        "360° Swivel",
      ],
      sku: "XP-OC-003",
      weight: "18kg",
      dimensions: "65x65x120 cm",
      supplierId: 2,
      supplierName: "ComfortHome Supplies",
    },
    {
      id: 4,
      name: "Stainless Steel Water Bottle",
      slug: "stainless-steel-water-bottle",
      category: "Sports & Outdoor",
      categoryId: 5,
      price: 24.99,
      bulkPrice: 15.0,
      moq: 100,
      stock: 2500,
      rating: 4.6,
      reviews: 756,
      image:
        "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600",
      images: [
        "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600",
      ],
      description:
        "Insulated stainless steel bottle keeps drinks cold for 24 hours, hot for 12 hours.",
      features: [
        "Double-Wall Insulation",
        "BPA-Free",
        "Leak-Proof",
        "750ml Capacity",
      ],
      sku: "XP-WB-004",
      weight: "320g",
      dimensions: "7x7x26 cm",
      supplierId: 3,
      supplierName: "EcoLife Products",
    },
    {
      id: 5,
      name: "Wireless Gaming Mouse",
      slug: "wireless-gaming-mouse",
      category: "Electronics",
      categoryId: 1,
      price: 59.99,
      bulkPrice: 42.0,
      moq: 50,
      stock: 670,
      rating: 4.4,
      reviews: 423,
      image:
        "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600",
      images: [
        "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600",
      ],
      description:
        "High-precision gaming mouse with customizable RGB lighting and 16,000 DPI sensor.",
      features: [
        "16,000 DPI",
        "RGB Lighting",
        "Programmable Buttons",
        "Wireless",
      ],
      sku: "XP-GM-005",
      weight: "95g",
      dimensions: "12x6x4 cm",
      supplierId: 1,
      supplierName: "TechGlobal Electronics",
    },
    {
      id: 6,
      name: "Leather Crossbody Bag",
      slug: "leather-crossbody-bag",
      category: "Fashion",
      categoryId: 2,
      price: 79.99,
      bulkPrice: 55.0,
      moq: 40,
      stock: 450,
      rating: 4.7,
      reviews: 267,
      image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600",
      images: [
        "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600",
      ],
      description:
        "Genuine leather crossbody bag with adjustable strap and multiple compartments.",
      features: [
        "Genuine Leather",
        "Adjustable Strap",
        "Multiple Pockets",
        "Zipper Closure",
      ],
      sku: "XP-CB-006",
      weight: "450g",
      dimensions: "25x18x8 cm",
      supplierId: 4,
      supplierName: "Fashion Forward Co.",
    },
    {
      id: 7,
      name: "Industrial Drill Set",
      slug: "industrial-drill-set",
      category: "Industrial Parts",
      categoryId: 4,
      price: 189.99,
      bulkPrice: 145.0,
      moq: 10,
      stock: 180,
      rating: 4.9,
      reviews: 92,
      image:
        "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600",
      images: [
        "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600",
      ],
      description:
        "Professional-grade drill set with 50+ bits and carrying case.",
      features: [
        "50+ Drill Bits",
        "Carrying Case",
        "Variable Speed",
        "Corded Electric",
      ],
      sku: "XP-ID-007",
      weight: "3.2kg",
      dimensions: "35x30x12 cm",
      supplierId: 5,
      supplierName: "Industrial Solutions Ltd",
    },
    {
      id: 8,
      name: "Organic Face Cream",
      slug: "organic-face-cream",
      category: "Health & Beauty",
      categoryId: 6,
      price: 34.99,
      bulkPrice: 22.0,
      moq: 60,
      stock: 890,
      rating: 4.6,
      reviews: 534,
      image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600",
      images: [
        "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600",
      ],
      description:
        "Natural organic face cream with vitamin E and hyaluronic acid for all skin types.",
      features: [
        "Organic Ingredients",
        "Vitamin E",
        "Hyaluronic Acid",
        "Cruelty-Free",
      ],
      sku: "XP-FC-008",
      weight: "50g",
      dimensions: "6x6x5 cm",
      supplierId: 6,
      supplierName: "Natural Beauty Co.",
    },
  ],

  // Suppliers
  suppliers: [
    {
      id: 1,
      name: "TechGlobal Electronics",
      slug: "techglobal-electronics",
      logo: "https://ui-avatars.com/api/?name=TG&background=2563eb&color=fff",
      rating: 4.8,
      reviews: 1250,
      location: "Shenzhen, China",
      categories: ["Electronics", "Gadgets"],
      certifications: ["ISO 9001", "CE", "RoHS"],
      responseTime: "< 2 hours",
      minOrder: "$500",
      productCount: 245,
      verified: true,
    },
    {
      id: 2,
      name: "ComfortHome Supplies",
      slug: "comforthome-supplies",
      logo: "https://ui-avatars.com/api/?name=CH&background=10b981&color=fff",
      rating: 4.6,
      reviews: 890,
      location: "Guangzhou, China",
      categories: ["Furniture", "Home Decor"],
      certifications: ["ISO 9001", "FSC"],
      responseTime: "< 4 hours",
      minOrder: "$1000",
      productCount: 156,
      verified: true,
    },
    {
      id: 3,
      name: "EcoLife Products",
      slug: "ecolife-products",
      logo: "https://ui-avatars.com/api/?name=EP&background=059669&color=fff",
      rating: 4.9,
      reviews: 567,
      location: "Portland, USA",
      categories: ["Eco-Friendly", "Sports"],
      certifications: ["B-Corp", "Fair Trade"],
      responseTime: "< 3 hours",
      minOrder: "$300",
      productCount: 89,
      verified: true,
    },
    {
      id: 4,
      name: "Fashion Forward Co.",
      slug: "fashion-forward-co",
      logo: "https://ui-avatars.com/api/?name=FF&background=ec4899&color=fff",
      rating: 4.5,
      reviews: 423,
      location: "Milan, Italy",
      categories: ["Fashion", "Accessories"],
      certifications: ["OEKO-TEX"],
      responseTime: "< 6 hours",
      minOrder: "$800",
      productCount: 189,
      verified: false,
    },
    {
      id: 5,
      name: "Industrial Solutions Ltd",
      slug: "industrial-solutions",
      logo: "https://ui-avatars.com/api/?name=IS&background=f59e0b&color=fff",
      rating: 4.7,
      reviews: 234,
      location: "Birmingham, UK",
      categories: ["Industrial", "Tools"],
      certifications: ["ISO 9001", "CE"],
      responseTime: "< 5 hours",
      minOrder: "$1500",
      productCount: 98,
      verified: true,
    },
    {
      id: 6,
      name: "Natural Beauty Co.",
      slug: "natural-beauty-co",
      logo: "https://ui-avatars.com/api/?name=NB&background=8b5cf6&color=fff",
      rating: 4.8,
      reviews: 678,
      location: "Los Angeles, USA",
      categories: ["Beauty", "Skincare"],
      certifications: ["Organic", "Cruelty-Free"],
      responseTime: "< 2 hours",
      minOrder: "$400",
      productCount: 167,
      verified: true,
    },
  ],

  // Orders
  orders: [
    {
      id: "XP-882711",
      date: "2026-01-15",
      status: "delivered",
      total: 420.0,
      items: 3,
      customer: "John Doe",
      shippingAddress: "123 Main St, New York, NY 10001",
      trackingNumber: "TRK-8827-1145-9923",
      products: [
        {
          productId: 1,
          name: "Wireless Bluetooth Headphones",
          quantity: 2,
          price: 89.99,
        },
        {
          productId: 4,
          name: "Stainless Steel Water Bottle",
          quantity: 10,
          price: 24.99,
        },
      ],
    },
    {
      id: "XP-882712",
      date: "2026-01-14",
      status: "shipped",
      total: 1250.0,
      items: 5,
      customer: "Jane Smith",
      shippingAddress: "456 Oak Ave, Los Angeles, CA 90001",
      trackingNumber: "TRK-8827-1146-8834",
      products: [
        {
          productId: 3,
          name: "Ergonomic Office Chair",
          quantity: 4,
          price: 299.99,
        },
        {
          productId: 5,
          name: "Wireless Gaming Mouse",
          quantity: 2,
          price: 59.99,
        },
      ],
    },
    {
      id: "XP-882713",
      date: "2026-01-13",
      status: "processing",
      total: 890.5,
      items: 8,
      customer: "Bob Johnson",
      shippingAddress: "789 Pine Rd, Chicago, IL 60601",
      trackingNumber: null,
      products: [
        {
          productId: 2,
          name: "Smart Fitness Watch",
          quantity: 5,
          price: 129.99,
        },
        {
          productId: 6,
          name: "Leather Crossbody Bag",
          quantity: 3,
          price: 79.99,
        },
      ],
    },
  ],

  // RFQ (Request for Quotation)
  rfqs: [
    {
      id: "RFQ-2401",
      date: "2026-01-15",
      status: "pending",
      product: "Wireless Bluetooth Headphones",
      quantity: 500,
      targetPrice: 60.0,
      deliveryDate: "2026-02-28",
      specifications: "Need custom branding and packaging",
      supplier: "TechGlobal Electronics",
      quotes: [],
    },
    {
      id: "RFQ-2402",
      date: "2026-01-14",
      status: "quoted",
      product: "Ergonomic Office Chair",
      quantity: 100,
      targetPrice: 200.0,
      deliveryDate: "2026-03-15",
      specifications: "Black color only, company logo embroidery",
      supplier: "ComfortHome Supplies",
      quotes: [
        {
          price: 215.0,
          leadTime: "45 days",
          moq: 100,
          notes: "Includes custom embroidery",
        },
      ],
    },
    {
      id: "RFQ-2403",
      date: "2026-01-12",
      status: "accepted",
      product: "Stainless Steel Water Bottle",
      quantity: 1000,
      targetPrice: 12.0,
      deliveryDate: "2026-02-20",
      specifications: "Custom color and logo printing",
      supplier: "EcoLife Products",
      quotes: [
        {
          price: 13.5,
          leadTime: "30 days",
          moq: 1000,
          notes: "Includes 2-color logo printing",
        },
      ],
    },
  ],

  // Warehouse Inventory
  warehouseInventory: [
    {
      sku: "XP-WH-001",
      name: "Wireless Bluetooth Headphones",
      stock: 1250,
      location: "A-12-04",
      status: "in-stock",
      reorderPoint: 200,
    },
    {
      sku: "XP-FW-002",
      name: "Smart Fitness Watch",
      stock: 890,
      location: "A-12-05",
      status: "in-stock",
      reorderPoint: 150,
    },
    {
      sku: "XP-OC-003",
      name: "Ergonomic Office Chair",
      stock: 340,
      location: "B-08-12",
      status: "in-stock",
      reorderPoint: 50,
    },
    {
      sku: "XP-WB-004",
      name: "Stainless Steel Water Bottle",
      stock: 2500,
      location: "C-15-02",
      status: "in-stock",
      reorderPoint: 500,
    },
    {
      sku: "XP-GM-005",
      name: "Wireless Gaming Mouse",
      stock: 120,
      location: "A-12-06",
      status: "low",
      reorderPoint: 100,
    },
    {
      sku: "XP-CB-006",
      name: "Leather Crossbody Bag",
      stock: 450,
      location: "D-03-08",
      status: "in-stock",
      reorderPoint: 80,
    },
    {
      sku: "XP-ID-007",
      name: "Industrial Drill Set",
      stock: 45,
      location: "E-20-01",
      status: "low",
      reorderPoint: 30,
    },
    {
      sku: "XP-FC-008",
      name: "Organic Face Cream",
      stock: 890,
      location: "F-05-15",
      status: "in-stock",
      reorderPoint: 200,
    },
  ],

  // Users
  users: [
    {
      id: 1,
      name: "John Doe",
      email: "john@example.com",
      role: "consumer",
      avatar: "https://ui-avatars.com/api/?name=John+Doe",
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "jane@business.com",
      role: "business",
      company: "Smith Enterprises",
      avatar: "https://ui-avatars.com/api/?name=Jane+Smith",
    },
    {
      id: 3,
      name: "Bob Johnson",
      email: "bob@dropship.com",
      role: "dropshipper",
      storefront: "Bob's Tech Store",
      avatar: "https://ui-avatars.com/api/?name=Bob+Johnson",
    },
    {
      id: 4,
      name: "Alice Wong",
      email: "alice@warehouse.com",
      role: "warehouse",
      facility: "Warehouse A",
      avatar: "https://ui-avatars.com/api/?name=Alice+Wong",
    },
    {
      id: 5,
      name: "Mike Chen",
      email: "mike@supplier.com",
      role: "supplier",
      company: "TechGlobal Electronics",
      avatar: "https://ui-avatars.com/api/?name=Mike+Chen",
    },
    {
      id: 6,
      name: "Admin User",
      email: "admin@gmail.com",
      password: "12345",
      role: "admin",
      avatar: "https://ui-avatars.com/api/?name=Admin+User",
    },
  ],

  // FAQ Data
  faqs: [
    {
      category: "Orders",
      questions: [
        {
          q: "How do I track my order?",
          a: "You can track your order by logging into your account and viewing the order details. A tracking number will be provided once your order ships.",
        },
        {
          q: "Can I cancel my order?",
          a: "Orders can be cancelled within 24 hours of placement. After that, please contact customer support for assistance.",
        },
        {
          q: "What payment methods do you accept?",
          a: "We accept all major credit cards, PayPal, and bank transfers for business accounts.",
        },
      ],
    },
    {
      category: "Shipping",
      questions: [
        {
          q: "What are the shipping costs?",
          a: "Shipping costs vary based on location and order size. Free shipping is available for orders over $100.",
        },
        {
          q: "How long does delivery take?",
          a: "Standard delivery takes 5-7 business days. Express shipping (2-3 days) is available for an additional fee.",
        },
        {
          q: "Do you ship internationally?",
          a: "Yes, we ship to over 150 countries worldwide. International shipping times vary by destination.",
        },
      ],
    },
    {
      category: "Returns",
      questions: [
        {
          q: "What is your return policy?",
          a: "We offer a 30-day return policy for most items. Products must be unused and in original packaging.",
        },
        {
          q: "How do I initiate a return?",
          a: 'Log into your account, go to order history, and click "Return Item" next to the product you wish to return.',
        },
        {
          q: "Who pays for return shipping?",
          a: "Return shipping is free for defective items. For other returns, customers are responsible for return shipping costs.",
        },
      ],
    },
  ],
};
